# 异构数据源 我要从两个数据库查询 数据

spring:
  datasource:
    dynamic:
      primary: hbase #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:

        # 名字可以自己定义
        hbase:
          url: jdbc:phoenix:hadoop102,hadoop103,hadoop104:2181
          username:
          password:
          driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver
        mysql:
          url: jdbc:mysql://hadoop102:3306/gmall2021
          username: root
          password: "000000"
          driver-class-name: com.mysql.jdbc.Driver